name: Update Manifest Version

on:
  release:
    # ‘created’ triggers as soon as the release (including drafts) is created, 
    # BEFORE the final source code archive for the release is frozen.
    types: [created]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Extract Version Number
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json
        run: |
          jq '.version = env.VERSION' custom_components/boschindego/manifest.json > tmp.json && mv tmp.json custom_components/boschindego/manifest.json

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manifest version to ${{ env.VERSION }} [skip ci]"
          file_pattern: 'custom_components/boschindego/manifest.json'
